#ifndef DRIVERSCONTAINER_CONFIG_H
#define DRIVERSCONTAINER_CONFIG_H

#include <stdint.h>

#define TCP_ACK_INTERVAL_MS		5000

#define ENCODER_MASTER_GPIO		23
#define ENCODER_SLAVE_GPIO		24

#define STEPPER_PWM_GPIO		10
#define STEPPER_DIR_GPIO		9
#define STEPPER_FREQ_HZ			1000

#define MOTOR_CUTTER_DIR_GPIO				26
#define MOTOR_CUTTER_PWM_GPIO				13

#define RELAY_CUTTER_ENB_GPIO				12
#define RELAY_ELECTROVALVES_GPIO			16

#define SENSOR_INIT_VERTICAL_SLAVE_GPIO		17
#define SENSOR_INIT_VERTICAL_MASTER_GPIO	4
#define SENSOR_INIT_HORIZONTAL_LEFT_GPIO	6
#define SENSOR_INIT_HORIZONTAL_RIGHT_GPIO	5
#define SENSOR_LASER_CUT_GPIO				11

#define LED_TRAFFIC_GPIO					27
#define LED_CONNECTION_GPIO					22

#define DC_MOTORS_FREQ_HZ				1000
#define DC_CUTTER_MOTOR_SPEED_CUT		200
#define DC_CUTTER_MOTOR_SPEED_RETURN	100

/* Vertical movement and encoders settings */
const float STEPS_PER_REVOLUTION		= 400;
const float MILIMETERS_PER_REVOLUTION 	= 30.00f;

const float VERTICAL_MM_OFFSET 			= 342;	/* 342mm */
const float VERTICAL_MAX_POSITION_MM 	= 2900;	/* 2.9m */

/* Debouncing */
const int ENCODER_DEBOUNCING_TIME_US 	= 0;
const int BUTTONS_DBOUNCING_TIME_MS 	= 1;

#endif //DRIVERSCONTAINER_CONFIG_H
